export const zhString = {
    'Add Node': '添加节点',
    'Add Group': '添加分组',
    'Edit Group': '编辑分组',
    'Clone': '复制',
    'Inputs': '输入',
    'Outputs': '输出',
    'Properties': '参数',
    'Properties Panel': '参数面板',
    'Title': '标题',
    'Mode': '运行模式',
    'Always': '每帧运行',
    'On Event': '事件触发',
    'Never': '从不运行',
    'On Trigger': '通用触发',
    'Resize': '自适应尺寸',
    'Collapse': '折叠',
    'Pin': '固定',
    'Color': '颜色',
    'Colors': '颜色',
    'Shapes': '形状',
    'Remove': '移除',
    'default': '默认',
    'box': '矩形',
    'round': '圆角',
    'card': '卡片',
    'Font size': '标题大小',

    'Rename Slot': '重命名节点',
    'Remove Slot': '移除节点',
    'Disconnect Links': '断开链接',
    'Add Reroute': '添加控制点',
    'Delete': '删除',
    'Expand': '展开',

    'graph': '蓝图',
    'Open': '打开',
    'Close subgraph': '关闭分支蓝图',


    'Align Selected To': '对齐选中节点',
    'Align' : '对齐',
    'Top': '顶部',
    'Bottom': '底部',
    'Left': '左边',
    'Right': '右边',
    'Distribute Nodes': '平均分配节点',
    'Vertically': '垂直',
    'Horizontally': '水平',
    'tips': '提示',
    

    'input':'输入',
    'middle':'中间',
    'output':'输出',
    'objects':'物件',
    'data':'数据',
    'value':'常数',
    'valueString':'文字',
    'button':'按下按键',
    'screen':'触摸屏',
    'phoneSensor':'动作感应',
    'event': '游戏内的变化',
    'controll':'摇杆',
    'controllHorizontal':'摇杆前后',
    'customButton':'自定义按键',
    'touchStart':'触摸开始',
    'touchMove': '触摸移动',
    'touchEnd': '触摸结束',
    'leftOrRightAct': '重力感应',
    'forwardOrbackAct':'前后倾斜',
    'shakeAct':'摇晃',
    'rotationAct':'转动',
    'gameStart':'开始时',
    'objectDestroy':'物体损坏时',
    'calculate':'计算',
    'covert': '转换',
    'angleCalculate':'角度计算',
    'compare':'比较',
    'inRange': '范围内',
    'logic':'逻辑',
    'change':'变化',
    'tool':'工具',
    'mapping':'映射',
    'toint':'取整数',
    'squareRoot':'平方根',
    'abs':'绝对值',
    'revertNegative':'正负反转',
    'dataObject': '数据结构',
    'getKeyValue': '数据取值',
    'angleDifference':'角度差',
    'vectorToAngel':'将位置转换为角度',
    'angleConvertVector':'将角度转换为位置',
    'allRight':'且',
    'orRight':'或',
    'notRight':'非',    //输入值为0时，输出1，输出值为0之外的值时，输出0
    'checkTag':'标记状态',
    'upCount': '计数',
    'timeDown': '倒计时',
    'randomNum': '随机数',
    'sendData':'无线传送发射',
    'acceptData':'无线传送接收',
    'writeNote':'个人备忘录',
    'exportObject':'引用物体',
    'media':'播放媒体',
    'time':'时间控制',
    'game':'游戏控制',
    'other': '其它',
    'bgm': '背景音',
    'sound': '声音',
    'vibrate':'震动',
    'stopTime':'停止时间',
    'timeScale':'时间缩放',
    'restartGame':'重新开始',
    'endGame':'游戏结束',
    'changeGame':'切换游戏',
    'showTextTip':'文字提示',
    'consoleInfo':'输出控制台',
    'showConfirm':'确认框',
    'showHandTip':'触摸提示',
    'blockTouch':'屏蔽触摸',
    'sprite':'绘制图片',
    'animate':'骨骼动画',
    'animates':'动画',
    'tween':'数值动画',
    'bezierCurve':'路径动画',
    'powerOfGod':'神秘力量',
    'objectSensor':'传感器',
    'space':'空间',
    'camera':'照相机',
    'createObject':'物体',
    'destroyObject':'销毁物体',
    'sendObject':'传送物体',
    'gravity':'引力',
    'contact':'接触感应器',
    'destroy':'销毁感应器',
    'position':'位置感应器',
    'speed':'其它感应器',
    'acceleration':'加速度感应器',
    'angle':'角度感应器',
    'angleSpeed':'角速度感应器',
    'connection': '连接零件',
    'layoutEx': '自动布局',
    'girdMap': '格子地图',
    'scrollRect':'滚动视图',
    'group': '物体成组',
    'getData':'获取数据',
    'setData':'记录数据',
    'controllData':'修改数据',
    'handData':'操作数据',
    'bagControll':'背包',
    'friend':'朋友',
    'systemData':'系统数据',
    'screenSize':'屏幕适配',
    'customData':'自定义数据',
    'userData':'玩家数据',
    'addBagGood':'添加物品',
    'useBagGood':'使用物品',
    'getFriend':'获取好友',
    'add': '加',
    'del': '减',
    'x': '乘',
    'chu': '除',
    'length': "长度",
    'equire': '等于',
    'litter': '小于',
    'bigger': '大于',
    'menu':'菜单',
    'startBtn':'运行',
    'previewBtn':'预览',
    'importBtn':'导入',
    'exportBtn':'导出到缓存',
    'downloadBtn':'下载到本地',
    'freshBtn': '刷新',
    'closeViewBtn': '关闭',
    'bigIcon':'大icon显示',
    'hideLine': '隐藏绿线',
    'debugMode': '预览Debug模式 OFF',
    'recordMode': 'recordMode',
    'clearBtn': '删除缓存',
    'showFps': 'showFps',
    'setting': '设置',
    'customComponent': '脚本组件',
    'inputArr': '输入扩展',
    'outputArr': '输出扩展',
    'outputLine': '输出逻辑线',
    'linkArr': '关联扩展',
    'lighting': '动态赋值',
    'lightingOut': '动态取值',
    'textCode': 'js文本'
}